### ISSUE TITLE
Bug when starting AppSync Simulator: TypeError: strToSplit.split is not a function

### ISSUE THREAD

**Issue by tux86** [bboure/serverless-appsync-simulator#108]
**Bug Intro**

To  reproduce this a error you should have  **serverless-appsync-simulator** and **serverless-offline** plugins and   cloudfront resource configuration for  appsync.

When starting offline mode with **serveress offline start** I got this error: 

```
AppSync Simulator: TypeError: strToSplit.split is not a function
```

**Bug description**

The bug is caused by appsync-simulator if you have  **Fn::Split** CF function in  **DomainName** of **Origin** section. See example below.

```
Resources:
  PublicApiDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        Comment: ${self:custom.PublicApiDomain}
        Aliases:
          - ${self:custom.PublicApiDomain}
        CustomErrorResponses: []
        ViewerCertificate:
          AcmCertificateArn: ${ssm:/${sls:stage}/global/acm_certificate_arn}
          SslSupportMethod: sni-only
        Origins:
          - Id: PublicApiOrigin
            DomainName:
              Fn::Select:
                - '2'
                - Fn::Split:
                    - /
                    - Fn::GetAtt:
                        - "Eventapipub${sls:stage}GraphQlApi"
                        - GraphQLUrl
```

**Temporary workaround**

Currently the only solution do disable this error in offline mode is to comment cf code for distribution.

**Comment by bboure** [comment]
Thank you @tux86 

This bug comes from the [cfn-resolver-lib](https://github.com/robessog/cfn-resolver-lib/blob/60175a75d27a5940c2cc25fe1810a2a2ffcffe8e/src/nodeTypes/FnSplit.js#L18) package (dependency of this plugin).

Please try to investigate what happens around these lines and see if the issue is in this plugin our `cfn-resolver-lib`

**Comment by tux86** [comment]
I have investigated the problem in **cfn-resolver-lib/src/nodeTypes/FnSplit.js**


`const strToSplit = this.directDependencies[1].evaluate();
`

strToSplit variable is supposed to contain a string but it's failing in this case because returned value is an array  [ 'EventapipubdevGraphQlApi', 'GraphQLUrl' ]. 

Fn::GetAtt  is not evaluated to string before evaluating Fn::Split: function.
```
                    - Fn::GetAtt:
                        - "Eventapipub${sls:stage}GraphQlApi"
                        - GraphQLUrl
```

As you can seen in the link below, the same issue already reported in the **cfn-resolver-lib** repository.
https://github.com/robessog/cfn-resolver-lib/issues/98

**Comment by tux86** [comment]
I have opened an issue in **cfn-resolver-lib** repo.

https://github.com/robessog/cfn-resolver-lib/issues/117

**Comment by tux86** [comment]
I resolved this issy by changing the way of generating appsync domain.
`
                      DomainName:
                        !Join
                          - '.'
                          - - !GetAtt Backendpriv${sls:stage}GraphQlApi.ApiId
                            - 'appsync-api'
                            - ${self:provider.region}
                            - 'amazonaws.com'
`

**Comment by adriantodt** [comment]
I stumbled on this same error, but managed to fix it by adding a override on getAttMap:

The evaluation at fault:
```yml
!Select [ 2, !Split [ '/', !GetAtt 'GraphQlApi.GraphQLUrl' ] ]
```

AppSync Simulator getAttMap override which fixed it:
```yml
custom:
  appsync-simulator:
    getAttMap:
      GraphQlApi: { GraphQLUrl: "https://unknown.amazonaws.com/graphql" }
```
