### ISSUE TITLE
Index n is out of bound when trying to manipulate AWS::StackId Ref

### ISSUE THREAD

**Issue by somq** [bboure/serverless-appsync-simulator#119]
Trying to split the StackId by using a `Fn::Split` inside a `Fn::Select` would crash the resolver.
I'm not sure if the issue is related to AppSync simulator or the offline plugin which would not resolve the StackId Ref because hardcoding it seems to fix the issue.

Error

```log
AppSync Simulator: Index 2 is out of bound.
```

Relevant crashing resource example

```yml
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      # What is before .auth.REGION.amazoncognito.com
      # @note get random UUID from the stack Id
      # @see https://stackoverflow.com/a/67162053/13169049
      Domain:
        Fn::Join:
          - '-'
          - - "myservicename"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - '-'
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId
```

It looks like the AWS::StackId does not get resolved by the offline plugin, hardcoding the StackId fixes the issue

```yml
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      # What is before .auth.REGION.amazoncognito.com
      # @note get random UUID from the stack Id
      # @see https://stackoverflow.com/a/67162053/13169049
      Domain:
        Fn::Join:
          - '-'
          - - "myservicename"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - '-'
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - arn:aws:cloudformation:us-west-2:123456789012:stack/teststack/51af3dc0-da77-11e4-872e-1234567db123
```

Any help would be greatly appreciated!
