### ISSUE TITLE
AppSync Simulator: TypeError: FnSplit is not a constructor

### ISSUE THREAD

**Issue by chaitanya11** [bboure/serverless-appsync-simulator#14]
**Describe the bug**
Unable to start appsync in local using this plugin.

getting error like this

AppSync Simulator: TypeError: FnSplit is not a constructor

using these packages

```
"serverless-appsync-simulator": "^0.3.4",
"serverless-offline": "^5.12.1",
"serverless-appsync-plugin": "1.1.2",
"serverless": "^1.61.2",
```

added in plugin sections like this

```
plugins:
  - serverless-webpack
  - serverless-appsync-simulator
  - serverless-offline
```

<img width="723" alt="Screenshot 2020-01-17 at 12 17 15 PM" src="https://user-images.githubusercontent.com/16046840/72590495-d3e72180-3923-11ea-8fd8-b28537091451.png">

**Comment by bboure** [comment]
@chaitanya11 I suspect this is related to the dependency `cfn-resolver-lib`
Are you using the Cfn `FnSplit` function somewhere in your yaml file?

**Comment by chaitanya11** [comment]
Yeah i am using that function, is that a problem? if so, can you suggest some alternative ?

**Comment by bboure** [comment]
@chaitanya11 Can you point out where you are using it and how in your yaml?
Maybe there is an alternative out a workaround for it.
Otherwise I guess you could also open an issue at https://github.com/robessog/cfn-resolver-lib to add support for it.

**Comment by chaitanya11** [comment]
@bboure i am using to attach subnetids to lambda function like bellow

  ```
rasaNlu:
    handler: src/api/rasa.rasaNlu
    timeout: 30
    layers:
      - ${opt:dhxds-layer}
    vpc:
      securityGroupIds:
        - ${opt:securityGroupId}
      subnetIds:
        "Fn::Split":
        - ","
        - ${opt:subnetIds}
```
