### ISSUE TITLE
plugin not working as expected after update depedencies

### ISSUE THREAD

**Issue by tttaisgt** [bboure/serverless-appsync-simulator#186]
**Describe the bug**
I'm using `serverless-appsync-simulator` with `serverless-offline` and `serverless-appsync-plugin` to simulate appsync(graphql) in local env

but after updated `serverless-offline` from `v7.0.0` to the `latest` version(because I upgrade nodejs version from 14.x->18.x and the old version of `serverless-offline` not support it), the simulator not working anymore, all the response is `null` and sometimes cause an error

**To Reproduce**
- run `sls offline start --host 0.0.0.0`
- go to GraphiQL screen
- make a request

**Expected behavior**
It can work normally

**Screenshots**
![image](https://github.com/serverless-appsync/serverless-appsync-simulator/assets/68092893/78ccea95-4387-46a2-9ac8-44a46cf56975)
![image](https://github.com/serverless-appsync/serverless-appsync-simulator/assets/68092893/4a36d1da-e9a9-4ce1-b2e1-c2b1741a78e8)

**Additional context**
**Sample Code**

- file: serverless.yml

```yaml
frameworkVersion: '3'
service: my-service

provider:
  runtime: nodejs18.x
  stage: dev

functions:
  main:
    handler: handler.main

appSync:
  name: Appsync
  authenticationType: API_KEY
  lambdaAuthorizerConfig:
      functionName: appsync-auth
  schema: ${file(./conf/schema.yml)}
  dataSources:
    - type: AWS_LAMBDA
          name: main
          description: 'Lambda DataSource'
          config:
            functionName: main
            iamRoleStatements:
              - Effect: "Allow"
                Action:
                  - "lambda:invokeFunction"
                Resource:
                  - "*"
  defaultMappingTemplates:
      request: false
      response: false
   mappingTemplates:
      - dataSource: main
        type: Query
        field: getData

appsync-simulator:
    watch: false
    port: 3000
    apiKey: da2-fakeApiId123456

plugins:
  - serverless-layers
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-offline
  - serverless-offline-direct-lambda
  - serverless-step-functions
```

- file: handler.js

```js
'use strict'

const { stringify } = JSON

exports.main = async function main() {
          callback(null, await controller.getData(event.arguments.request, event.info.selectionSetList));
}
```

- file: controller
```js
getData(request) {
  result = # process request...
  return { data: result };
}
```

- file: data.graphql
```graphql
type Query {
    getData(id:Int!):Data
}

type Data {
    id:Int
    name:String
    type:String
    created_at:AWSDateTime
    deleted:Boolean
    updated_at:AWSDateTime
}
```

**Environment**

- `serverless`: v3.31.0
- `serverless-offline`: v12.0.4
- `serverless-appsync-simulator`: v0.20.0
- `node.js` version: nodejs18.x
- `OS`: macOS monterey 12.6.5
