### ISSUE TITLE
AppSync Simulator: TypeError: (appSyncConfig.mappingTemplates || []).flat is not a function

### ISSUE THREAD

**Issue by carlosdubus** [bboure/serverless-appsync-simulator#40]
```
plugins:
  - serverless-appsync-plugin
  - serverless-dynamodb-local # only if you need dynamodb resolvers and you don't have an external dynamodb
  - serverless-appsync-simulator
  - serverless-offline
custom:
  appSync:
    name: stores-api
    schema: schema.graphql
    authenticationType: API_KEY
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: hello
        type: Query
        field: hello
        request: Query.hello.request.vtl
        response: Query.hello.response.vtl
    dataSources:
      - type: AWS_LAMBDA
        name: hello
        description: 'Lambda DataSource'
        config:
          functionName: hello
  appsync-offline:
    port: 62222
    dynamodb:
      server:
        port: 8000
```
