### ISSUE TITLE
GetAttResolvers not found in params file

### ISSUE THREAD

**Issue by NathanH81** [bboure/serverless-appsync-simulator#46]
Thank you to all contributors for this library! I am having trouble getting my resolvers to run with the following setup in my serverless.yml file. I think I need to make a change to the getAttMap option in the custom section but I'm not sure how to resolve it. Any advice on how to resolve this?

My dataSources gets the IAMRole Arn like so:

```
dataSources:
  - type: AWS_LAMBDA
    name: getBorrower
    config:
      functionName: getBorrower
      serviceRoleArn: { Fn::GetAtt: [AWSAppSyncIAMRole, Arn] }
```
This gives the following error:

```
Fn::GetAttResolvers not found in params file: AWSAppSyncIAMRole
```

For reference, the resources part of my serverless.yml file.

```
resources:
  Resources:
    AWSAppSyncIAMRole:
      Type: AWS::IAM::Role
