### ISSUE TITLE
API server start fails using Fn::GetAtt with no Resources block

### ISSUE THREAD

**Issue by jeffycyang** [bboure/serverless-appsync-simulator#48]
**Describe the bug**
I'm experiencing something similar to this [issue](https://github.com/bboure/serverless-appsync-simulator/issues/20), although my error instead is `AppSync Simulator: TypeError: Cannot read property 'findWrappedResource' of undefined` (same error as this [issue](https://github.com/bboure/serverless-appsync-simulator/issues/9)) and thus the simulator fails to start.

In my case, I'm using [serverless-appsync-plugin](https://github.com/sid88in/serverless-appsync-plugin#configuring-the-plugin)'s default `logConfig`:
```
      logConfig:
        loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] } # Where AppSyncLoggingServiceRole is a role with CloudWatch Logs write access
        level: ERROR
        excludeVerboseContent: false
```

Even though I've defined the following in `custom.appsync-simulator` in my `serverless.yml`:
```
    getAttMap:
      AppSyncLoggingServiceRole:
        Arn: "mockAppSyncLoggingServiceRoleArn"
```

**To Reproduce**
Add
```
      logConfig:
        loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
        level: ERROR
        excludeVerboseContent: false
```
to `custom.appSync` and
```
    getAttMap:
      AppSyncLoggingServiceRole:
        Arn: "mockAppSyncLoggingServiceRoleArn"
```
in `custom.appsync-simulator` in `serverless.yml`

**Expected behavior**
There should be no error when starting the API server and the value should be taken from `custom.appsync-simulator.getAttMap`.

**Screenshots**
![](https://user-images.githubusercontent.com/13949695/94611484-a2ff1080-0256-11eb-9cd2-9c1d6095fdaf.png)

**Additional context**
Similar to this [issue](https://github.com/bboure/serverless-appsync-simulator/issues/20), I've been able to circumvent the error by defining an empty resources block like so:
```
resources:
  Resources: # nothing here
plugins:
  - serverless-appsync-simulator
  - serverless-offline
  - serverless-appsync-plugin
```
but with no resources defined, which, as far as I can tell, creates a `ResourcesNode` so the `findWrappedResource` property is at least defined and the simulator starts.

This is a decent workaround at the moment, since I don't actually require the `loggingRoleArn` locally so this isn't high priority by any means.  But the requirement to have `resources` defined even if it's empty creates a bit of cognitive dissonance and should not be necessary.

As always, thanks for your work on this plugin, it has made debugging and working with AppSync APIs locally actually possible for me 👍
