### ISSUE TITLE
Connection to external DynamoDB does not work if you have protected Dynamo with Session Token

### ISSUE THREAD

**Issue by Scale93** [bboure/serverless-appsync-simulator#76]
**The security token included in the request is invalid**
I Have included appsync-simulator inside my serverless project, I'm trying to connect it with my remote DynamoDB resource on AWS that is protected through a session token. 

"serverless-appsync-simulator" give me the ability to configure 4 parameter to connect itself with external DynamoDB:
```
custom:
  appsync-simulator:
    apiKey: 0123456789
    port: 20002
    dynamoDb:
      endpoint: https://dynamodb.eu-central-1.amazonaws.com
      region: eu-central-1
      accessKeyId: DEFAULT_ACCESS_KEY
      secretAccessKey: DEFAULT_SECRET
```

(Default values of accessKeyId and secretAccessKey are written on my .aws/credential file!)
I have also tried to write accessKeyId and secretAccessKey inside my "serverless.yml" file.

If I run "sls offline start" and try to make a query, AppSync Simulator give me back an error message:
```
message "The security token included in the request is invalid."
code: "UnrecognizedClientException"
```

I have an updated token in my .aws/credential file, so I think that the problem could be that AppSync Simulator does not support authentication with the session token.

My expectation is to find another configuration parameter under dynamoDb:
```
custom:
  appsync-simulator:
    apiKey: 0123456789
    port: 20002
    dynamoDb:
      endpoint: https://dynamodb.eu-central-1.amazonaws.com
      region: eu-central-1
      accessKeyId: DEFAULT_ACCESS_KEY
      secretAccessKey: DEFAULT_SECRET
      sessionToken: DEFAULT_SESSION_TOKEN ???
```

Is there a workaround to solve this issue?
