### ISSUE TITLE
Error: UnauthorizedException: Missing authorization

### ISSUE THREAD

**Issue by skix123** [bboure/serverless-appsync-simulator#89]
A few seconds after running `sls offline start` (no additional action required) the following error occurs: 

```
Error: UnauthorizedException: Missing authorization
    at Object.getAuthorizationMode (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/utils/auth-helpers/current-auth-mode.js:56:11)
    at AppSyncSimulatorSubscriptionServer.authorizeRequest (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/websocket-subscription.js:80:35)
    at AppSyncSimulatorSubscriptionServer.onConnect (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/websocket-subscription.js:77:19)
    at WebsocketSubscriptionServer.<anonymous> (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:134:59)
    at step (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:63:23)
    at Object.next (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:44:53)
    at /Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:34:12)
    at WebSocketServer.WebsocketSubscriptionServer.onSocketConnection (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:114:71)
    at WebSocketServer.emit (events.js:315:20)
    at WebSocketServer.EventEmitter.emit (domain.js:486:12)
    at WebSocketServer.completeUpgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:330:5)
    at WebSocketServer.handleUpgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:246:10)
    at Server.upgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:92:16)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:486:12)
    at onParserExecuteCommon (_http_server.js:695:14)
    at onParserExecute (_http_server.js:608:3)
```

Here's my `serverless.yml`:
```
service: radvana-api
frameworkVersion: ^2.34.0
variablesResolutionMode: 20210326
useDotenv: True

plugins:
    - serverless-appsync-plugin
    - serverless-appsync-simulator
    - serverless-offline

provider:
    name: aws
    region: eu-central-1
    runtime: nodejs14.x
    stage: ${opt:stage, 'local'}
    lambdaHashingVersion: '20201221'
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - lambda:*
                  Resource:
                      - arn:aws:lambda:${self:provider.region}:*:*
    environment:
        REGION: '${self:provider.region}'
        STAGE: '${self:provider.stage}'
        APPSYNC_NAME: '${self:custom.defaultPrefix}-appsync'
        MYSQL_HOST: ${env:MYSQL_HOST, ssm:mysql_host}
        MYSQL_DB: ${env:MYSQL_DB, ssm:mysql_db}
        MYSQL_USER: ${env:MYSQL_USER, ssm:mysql_user}
        MYSQL_PASSWORD: ${env:MYSQL_PASSWORD, ssm:mysql_password}

custom:
    appSync:
        name: '${self:provider.environment.APPSYNC_NAME}'
        authenticationType: AMAZON_COGNITO_USER_POOLS
        serviceRole: ' AppSyncCognitoUserPool'
        dataSources: ${file(resources/data-sources.yml)}
        mappingTemplates: ${file(resources/resolvers.yml)}
        userPoolConfig:
            defaultAction: DENY
            userPoolId: eu-central-REDACTED
    appsync-simulator:
        port: 4000
        watch:
            - 'schema.graphql'
            - ['match', 'mapping-templates/**/*.vtl', 'wholename']
            - ['match', 'dist/**/*.js', 'wholename']

    defaultPrefix: ${self:service}-${self:provider.stage}

functions:
    - ${file(resources/lambda-functions.yml)}

resources:
    - ${file(resources/user-pool.yml)}
```

This error keeps occurring every few seconds.

Note that the API works correctly and I'm able to make graphql requests and receive results.
